# Generated by Django 5.2.7 on 2025-10-18 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('badge_type', models.CharField(choices=[('contributor', 'Top Contributor'), ('innovator', 'Innovative Thinker'), ('collaborator', 'Great Collaborator'), ('helper', 'Helpful Member'), ('expert', 'Domain Expert'), ('pioneer', 'Early Adopter')], max_length=50, unique=True)),
                ('description', models.TextField()),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('criteria', models.TextField(help_text='Requirements to earn this badge')),
                ('points_required', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_points', models.IntegerField(default=0)),
                ('ideas_posted', models.IntegerField(default=0)),
                ('comments_made', models.IntegerField(default=0)),
                ('upvotes_received', models.IntegerField(default=0)),
                ('resources_shared', models.IntegerField(default=0)),
                ('events_organized', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'User Points',
                'ordering': ['-total_points'],
            },
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awarded_to', to='gamification.badge')),
            ],
            options={
                'ordering': ['-earned_at'],
            },
        ),
    ]
